### PR TITLE
New york times article page clone feature a

### PR DESCRIPTION
**Pull request by KossySteve**
This is a clone of the New York TImes article page

### CODE REVIEW

**Comment by KossySteve** [comment]
This is a clone of New York Times page

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @meme-es and @KossySteve 

### You have done really great, however, there are a few changes you need to make for your project to be approved.

- Write a more descriptive pull request, [check this guide](https://github.com/microverseinc/readme-template)
- Validate your html code using this [tool](https://validator.w3.org/#validate_by_upload)
- Avoid using inline css in your html code
- Make your sidebar better, refer original [website](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)
- Also, make your footer better, refer original [website](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)
- Use grid and position to achieve this area, it is not an image
not image
- Add .gitignore to your root directory and add not needed files in there [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)
- Configure your linter properly [check this guide](https://github.com/microverseinc/linters-config/tree/master/css)

### Once you have made all these changes, resubmit for another review. I wish you all the best.
- For questions, you can reach me on slack
Happy coding!

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi Team, you have done a great job so far. :slightly_smiling_face:  You made great changes requested by the previous reviewer. :+1:  Kindly fix the below comments and submit code review
- Kindly fix linter errors
lint

- Kindly fix this section 
Your version
anoda
Original
pure

- The footer should have a fixed position
f

- Kindly fix the horizontal scroll
hrs2

Kindly make these changes and submit code review :slightly_smiling_face: 
Happy coding :computer:

**Comment by meme-es** [comment]
In the last fixes Stickler says that we have to use box-model, but when we use box-model Stickler says then that box-model is not compatible whit IE6 & IE7 :S.

**Review by Forison — CHANGES_REQUESTED** [review]
#### Status: Require changes🛑
# hi team🙌.
Your project looks good but there are a few issues to address before we can get it approved
* [ ] The bottom of the pages is a bit messy now, here is how it looks👇,
Screenshot from 2020-01-30 16-30-08
here is how the original looks👇
Screenshot from 2020-01-30 16-31-43

* [ ] Linters have to pass in other for a project to be approved. Here is a clue the error is occurring because you are setting height and padding on an element and different browsers have a different way of interpreting this. Let us find a way to bypass this error.

## That is it, makes these changes and submit the project for review😇
### Happy coding😇
### Addo Forison

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi team, 👋 

### Great job implementing the suggested changes. 🙌 However, the stickler has some errors, let's fix that.

**Kindly submit for another code review once this has been done.** _Happy coding!_ 💯

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @KossySteve @meme-es 
- I noticed that you made changes to linters config files, you shouldn't make changes to these files, kindly use the files in this [guide](https://github.com/microverseinc/linters-config/tree/master/css), see screenshot of [requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png)

## Kindly make the suggested changes then request for another code review.
### Status: Changes Required
_Feel free to reach out to me on slack (Fatima) if you have any questions, I'd be happy to help._

**Comment by meme-es** [comment]
Stickler says: 
Your eslint config file is missing or invalid. Please ensure that ./eslint.config exists and is valid.
What's about that?

**Comment by fatymahmed** [comment]
> Stickler says:
> Your eslint config file is missing or invalid. Please ensure that ./eslint.config exists and is valid.
> What's about that?


Hi @meme-es, you changed your stickler.yml file, that's why it requires eslint.config file, however, if you use [this](https://github.com/microverseinc/linters-config/blob/master/css/.stickler.yml) stickler.yml file provided by microverse, you won't need the eslint file.

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Comment by meme-es** [comment]
Thank you guys, for all your support!

**Pull request merged**
